import { StyleSheet, Dimensions } from 'react-native';
import theme from '../../config/theme';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');
const isSmallScreen = SCREEN_HEIGHT < 700;

export default StyleSheet.create({
  container: {
    ...theme.common.container,
    backgroundColor: theme.colors.background.paper,
  },
  header: {
    ...theme.common.spaceBetween,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: isSmallScreen ? theme.spacing.xs : theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.light,
    ...theme.shadows.apply({}, 'xs'),
    flexShrink: 0,
  },
  backButton: {
    padding: theme.spacing.xs,
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: isSmallScreen ? 16 : 18,
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  placeholderRight: {
    width: 40,
    height: 40,
  },
  content: {
    flex: 1,
    justifyContent: 'space-between',
    paddingBottom: theme.spacing.md,
  },
  titleSection: {
    alignItems: 'center',
    paddingHorizontal: theme.spacing.md,
    paddingTop: isSmallScreen ? theme.spacing.sm : theme.spacing.md,
    paddingBottom: isSmallScreen ? theme.spacing.xs : theme.spacing.sm,
    flexShrink: 1,
  },
  iconContainer: {
    width: isSmallScreen ? 60 : 70,
    height: isSmallScreen ? 60 : 70,
    borderRadius: isSmallScreen ? 30 : 35,
    backgroundColor: `${theme.colors.primary.main}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: isSmallScreen ? theme.spacing.xs : theme.spacing.sm,
  },
  mainTitle: {
    fontSize: isSmallScreen ? 20 : 24,
    color: theme.colors.text.primary,
    fontWeight: 'bold',
    marginBottom: isSmallScreen ? theme.spacing.xxs : theme.spacing.xs,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: isSmallScreen ? 12 : 14,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    lineHeight: isSmallScreen ? 16 : 20,
    paddingHorizontal: theme.spacing.sm,
  },
  tableContainer: {
    marginHorizontal: theme.spacing.md,
    marginTop: isSmallScreen ? theme.spacing.xs : theme.spacing.sm,
    backgroundColor: theme.colors.background.input,
    borderRadius: theme.borders.radius.md,
    overflow: 'hidden',
    ...theme.shadows.apply({}, 'sm'),
    flexShrink: 1,
  },
  tableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: isSmallScreen ? theme.spacing.sm : theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    backgroundColor: theme.colors.primary.main,
    borderBottomWidth: 2,
    borderBottomColor: theme.colors.primary.dark,
  },
  tableHeaderText: {
    fontSize: isSmallScreen ? 13 : 15,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: isSmallScreen ? theme.spacing.sm : theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.light,
    minHeight: isSmallScreen ? 44 : 52,
  },
  tableRowEven: {
    backgroundColor: theme.colors.background.paper,
  },
  featureText: {
    fontSize: isSmallScreen ? 12 : 14,
    color: theme.colors.text.primary,
    flex: 1,
    marginRight: theme.spacing.sm,
    lineHeight: isSmallScreen ? 16 : 20,
  },
  checkContainer: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pricingSection: {
    alignItems: 'center',
    marginTop: isSmallScreen ? theme.spacing.sm : theme.spacing.md,
    marginHorizontal: theme.spacing.md,
    paddingVertical: isSmallScreen ? theme.spacing.sm : theme.spacing.md,
    backgroundColor: theme.colors.background.input,
    borderRadius: theme.borders.radius.md,
    ...theme.shadows.apply({}, 'sm'),
    flexShrink: 0,
  },
  priceLabel: {
    fontSize: isSmallScreen ? 12 : 14,
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing.xxs,
  },
  price: {
    fontSize: isSmallScreen ? 24 : 28,
    color: theme.colors.primary.main,
    fontWeight: 'bold',
    marginBottom: theme.spacing.xxs,
  },
  priceNote: {
    fontSize: isSmallScreen ? 10 : 12,
    color: theme.colors.text.secondary,
  },
  payButton: {
    marginTop: isSmallScreen ? theme.spacing.sm : theme.spacing.md,
    marginHorizontal: theme.spacing.md,
    paddingVertical: isSmallScreen ? theme.spacing.sm : theme.spacing.md,
    backgroundColor: theme.colors.primary.main,
    borderRadius: theme.borders.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    ...theme.shadows.apply({}, 'md'),
    flexShrink: 0,
  },
  payButtonText: {
    fontSize: isSmallScreen ? 14 : 16,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});
